using System;
using System.Collections.Generic;
using System.Text;
using System.Data.SQLite;

namespace OpcodeDiffer
{
    /// <summary>
    /// Class to access SQLite databases
    /// </summary>
    public class SQLiteDB
    {
        protected SQLiteConnection dbConnection;
        protected SQLiteDataReader reader;

        public SQLiteDB(string dbPath)
        {
            dbConnection = new SQLiteConnection(string.Format("Data Source={0};FailIfMissing=True;", dbPath));
            dbConnection.Open();
        }
        
        public bool isOpen()
        {
            return dbConnection.State == System.Data.ConnectionState.Open;
        }

        protected void closeReaderIfOpen()
        {
            if (reader != null)
            {
                if (!reader.IsClosed)
                    reader.Close();
            }
        }

        ~SQLiteDB()
        {
            dbConnection.Dispose();
        }
    }

    /// <summary>
    /// Class specific to accessing SQLite database generated by BinDiff
    /// </summary>
    public class DiffDB : SQLiteDB
    {
        public DiffDB(string dbPath) : base(dbPath) 
        {
            getAddr2FromAddr1 = new SQLiteCommand("SELECT address2 FROM function WHERE address1=@addr1", dbConnection);
            getConfidenceFromAddr1 = new SQLiteCommand("SELECT confidence FROM function WHERE address1=@addr1", dbConnection);
        }

        SQLiteCommand getAddr2FromAddr1;
        SQLiteCommand getConfidenceFromAddr1;

        public UInt32 GetAddr2FromAddr1(UInt32 addr1)
        {
            getAddr2FromAddr1.Parameters.AddWithValue("@addr1", addr1);

            return Convert.ToUInt32(getAddr2FromAddr1.ExecuteScalar());

        }

        public double GetConfidenceFromAddr1(UInt32 addr1)
        {
            getConfidenceFromAddr1.Parameters.AddWithValue("@addr1", addr1);

            return (double)getConfidenceFromAddr1.ExecuteScalar();
        }
    }

    /// <summary>
    /// Generic prototype class to acces an SQLite database generated by WoWOpcodeDumper
    /// </summary>
    public class ProtoDumpDB : SQLiteDB
    {
        public struct Version
        {
            public Version(int clientBuild, double cumperVersion) : this()
            {
                this.clientBuild = clientBuild;
                this.dumperVersion = dumperVersion;
            }

            public int clientBuild { get; private set; }
            public double dumperVersion { get; private set; }
        }

        protected ProtoDumpDB(string dbPath)
            : base(dbPath)
        {
            CMSG_getCallerFromOpcode = new SQLiteCommand("SELECT caller FROM CMSG WHERE opcode=@opcode", dbConnection);
            SMSG_getHandlerFromOpcode = new SQLiteCommand("SELECT handler FROM SMSG WHERE opcode=@opcode", dbConnection);

            // Get DB version
            SQLiteCommand getDbVersion = new SQLiteCommand("SELECT * FROM Version", dbConnection);
            SQLiteDataReader versionReader = getDbVersion.ExecuteReader();

            versionReader.Read();
            dbVersion = new Version(versionReader.GetInt32(0), versionReader.GetDouble(1));

            // Dispose
            versionReader.Dispose();
            getDbVersion.Dispose();
        }

        Version dbVersion;
        SQLiteCommand CMSG_getCallerFromOpcode;
        SQLiteCommand SMSG_getHandlerFromOpcode;

        public UInt32 CMSG_GetCallerFromOpcode(int opcode)
        {
            // Write parameter
            CMSG_getCallerFromOpcode.Parameters.AddWithValue("@opcode", opcode);

            // Run Query
            return (UInt32)CMSG_getCallerFromOpcode.ExecuteScalar();
        }
        public UInt32 SMSG_GetHandlerFromOpcode(int opcode)
        {
            // Write parameters
            SMSG_getHandlerFromOpcode.Parameters.AddWithValue("@opcode", opcode);

            // Run query
            return (UInt32)SMSG_getHandlerFromOpcode.ExecuteScalar();
        }
        
    }

    /// <summary>
    /// Class to access a named SQLite database designed to be diffed against
    /// </summary>
    public class NameDB : ProtoDumpDB
    {
        public NameDB(string dbPath)
            : base(dbPath)
        {
            writeNameCmd = new SQLiteCommand("UPDATE @type set name=@name WHERE opcode=@opcode", dbConnection);
            CMSG_getNameFromCaller = new SQLiteCommand("SELECT name FROM CMSG WHERE caller=@caller", dbConnection);
            SMSG_getNameFromHandler = new SQLiteCommand("SELECT name FROM SMSG WHERE handler=@handler", dbConnection);
        }

        SQLiteCommand writeNameCmd;
        SQLiteCommand CMSG_getNameFromCaller;
        SQLiteCommand SMSG_getNameFromHandler;

        public void CMSG_writeName(int opcode, string name)
        {
            // Write parameters
            writeNameCmd.Parameters.AddWithValue("@type", "CMSG");
            writeNameCmd.Parameters.AddWithValue("@name", name);
            writeNameCmd.Parameters.AddWithValue("@opcode", opcode);

            // Execute query and clear parameters
            writeNameCmd.ExecuteNonQuery();
            writeNameCmd.Parameters.Clear();
        }
        public void SMSG_writeName(int opcode, string name)
        {
            // Write parameters
            writeNameCmd.Parameters.AddWithValue("@type", "SMSG");
            writeNameCmd.Parameters.AddWithValue("@name", name);
            writeNameCmd.Parameters.AddWithValue("@opcode", opcode);

            // Execute query and clear parameters
            writeNameCmd.ExecuteNonQuery();
            writeNameCmd.Parameters.Clear();
        }
        public string SMSG_GetNameFromHandler(UInt32 handler)
        {
            // Add parameter
            SMSG_getNameFromHandler.Parameters.AddWithValue("@handler", handler);

            // Execute query
            var name = SMSG_getNameFromHandler.ExecuteScalar();
            if (name != DBNull.Value)
                return (string)name;
            else
                return String.Empty;

        }
        public string CMSG_GetNameFromCaller(UInt32 caller)
        {
            // Add parameter
            CMSG_getNameFromCaller.Parameters.AddWithValue("@caller", caller);

            // Execute query
            var name = CMSG_getNameFromCaller.ExecuteScalar();
            if (name != DBNull.Value)
                return (string)name;
            else
                return String.Empty;
        }
    }

    /// <summary>
    /// Class to access SQLite database generated by dumper
    /// </summary>
    public class DumpDB : ProtoDumpDB
    {
        public DumpDB(string dbPath) :
            base(dbPath)
        {
            CMSG_get = new SQLiteCommand("SELECT * FROM CMSG WHERE opcode=@opcode", dbConnection);
            SMSG_get = new SQLiteCommand("SELECT * FROM SMSG WHERE opcode=@opcode", dbConnection);
        }

        SQLiteCommand CMSG_get;
        SQLiteCommand SMSG_get;

        public CMSG CMSG_Get(int opcode)
        {
            // Write parameter
            CMSG_get.Parameters.AddWithValue("@opcode", opcode);

            // Execute Query
            closeReaderIfOpen();
            reader = CMSG_get.ExecuteReader();
            if (reader.Read())
                return new CMSG(reader.GetInt32(0), (UInt32)reader.GetInt32(1), (UInt32)reader.GetInt32(2), (UInt32)reader.GetInt32(3));
            else
                return null;
        }
        public SMSG SMSG_Get(int opcode)
        {
            // Write parameter
            SMSG_get.Parameters.AddWithValue("@Opcode", opcode);

            // Execute Query
            closeReaderIfOpen();
            reader = SMSG_get.ExecuteReader();
            if (reader.Read())
                return new SMSG(reader.GetInt32(0), (UInt32)reader.GetInt32(1), (UInt32)reader.GetInt32(2), (UInt32)reader.GetInt32(3));
            else
                return null;
        }
    }
}

